name: Keep Backend Active

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping to keep server alive
        run: |
          curl -X GET ${{secrets.BACKEND_URL}} || echo "Server ping failed"
